apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-app
spec:
  type: ClusterIp
  selector:
    app: example-app
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000

